### ISSUE TITLE
How did you get colored synthetic images in the paper when the mesh has no texture?

### ISSUE THREAD

**Issue by Guptajakala** [hughw19/NOCS_CVPR2019#20]
The object mesh currently provided has no texture. But in the paper, you mentioned mixed reality rendering where the objects in the example images have colors. I'm wondering if you could provide the texture you were using for future similar work benchmarking.

**Comment by hughw19** [comment]
Hi Hoja,

The mixed reality data only leverages synthetic object models from ShapeNet, which do have textures. For real data, we just train on it without composing the real objects with other backgrounds. 

The reason is that we believe synthetic data is capable to provide sufficiently diversity and can transfer to real. Real data capture with 6D pose annotated is too expensive to scale up, so we can only capture few. In our project, the small amount of real training data is used only to mitigate the domain gap but not designated to cover shape and texture variance.

There is currently no plan to provide perfect object mesh and textures for our small amount of real objects. We don’t encourage people to leverage any real object models since they should be unknown at test time. 


Best,
He

**Comment by Guptajakala** [comment]
@hughw19 Thanks, that makes a lot of sense!
