### ISSUE TITLE
Question for object scale

### ISSUE THREAD

**Issue by linyangsdu** [hughw19/NOCS_CVPR2019#34]
I have a question for object scale estimation. For nocs, it is a normalized space, how can you get predict scale result from pred coord?

**Comment by hughw19** [comment]
Sorry for the delay. My mail wasn't sent and stay in the outbox.

The transformation between NOCS and depth point cloud is a 7D similarity transformation, including 1D scale + 6D pose. Through pose fitting using Umeyama algorithm, we can obtain 1D scale. Using the spatial extent information in the predicted NOCS, we can know the 3D aspect ratio.


Best,
He

**Comment by linyangsdu** [comment]
So, dose this mean scale info is contained in nocs? because scale is always less than 1, so we can obtain scale directly from predict nocs using np.amax.

**Comment by hughw19** [comment]
No, the scale in NOCS is normalized, which means ideally (x_max-x_min)^2+(y...)^2 + (z...)^2 = 1.

You need to solve the 7D similarity transformation between NOCS and depth to get scale.

However, since this is a similarity transformation, you can expect the 3D aspect ratio is the same. So, from NOCS, you can get 3D aspect ratio, which can be estimated as (2*max(|x_max|, |x_min|), ...). You can multiply this aspect ratio by fitted scale to get real 3D dimension.

Best,
He

**Comment by linyangsdu** [comment]
Okay, thank you for your explanation.
